name: Build
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "*.md"

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "*.md"

jobs:
  prebuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - data: [18, 20]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        env:
          CFG: ${{ toJSON(matrix.cfg) }}
        run: jq -r -n 'env.CFG | fromjson | @json "matrix=\(.data)"' >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [prebuild]

    strategy:
      matrix:
        node-version: ${{ fromJson(needs.prebuild.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Build
      run: |
        npm ci
        npm run build
