name: Release Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump-version-and-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: |
          npm version patch --force
          echo "::set-output name=new_version::$(node -pe "require('./package.json').version")"

      - name: Push changes
        run: |
          git push origin main --follow-tags

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump-version.outputs.new_version }}
          release_name: Release ${{ steps.bump-version.outputs.new_version }}
          draft: false
          prerelease: false
